### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by pcsforeducation** [pusher/pusher-rest-python#3]
My server and dev vm are set to UTC and got this error. I reconfigured for Pacific, and it no longer complains.

push.models ERROR Unable to send requests to push: Timestamp expired: Given timestamp (2015-01-13T03:22:02Z) not within 600s of server time (2015-01-13T03:39:10Z)
Traceback (most recent call last):
  File "/home/docker/code/push/models.py", line 88, in send_all
    p.trigger([settings.PUSHER_CHANNEL], unicode(message_type), data)
  File "/usr/local/lib/python2.7/dist-packages/pusher/pusher.py", line 20, in __call__
    return self.pusher.backend.send_request(self.make_request(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/pusher/sync.py", line 38, in send_request
    return process_response(resp.status, body)
  File "/usr/local/lib/python2.7/dist-packages/pusher/util.py", line 42, in process_response
    raise PusherBadAuth(body)
PusherBadAuth: Timestamp expired: Given timestamp (2015-01-13T03:22:02Z) not within 600s of server time (2015-01-13T03:39:10Z)

**Comment by ibnfarouk** [comment]
i have same issue , working on Mac and have Laravel timezone to "UTC"

**Comment by mdpye** [comment]
Are you sure your clock was correct before you reconfigured it? The response  shows that the timestamp from your request was 17 minutes behind the actual time. Perhaps when reconfiguring you also corrected that.

It if really were a timezone issue, I'd expect to see it out by some whole (or half in a handful of cases) number of hours, and if it were related to UTC/Pacific then it would be 7 or 8 hours different.

**Comment by mdpye** [comment]
Sorry, just realised the original comment is rather (!!) old. @ibnfarouk check your clock is actually accurate. The response from the server provides both the timestamp you submitted and the time from the server.

**Comment by ibnfarouk** [comment]
@mdpye

Thanks alot .. worked by adding an hour to my Mac clock

**Comment by Natgho** [comment]
I have same issue, Is anyone working on this issue?

Edit: I Solved this problem. 
I am talking for Mac, Clock -> set date and time -> mark "automatic configuration"

**Comment by digitlimit** [comment]
If you are on a local machine restarting your system resync your time
